name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        expo-cache: false
        eas-cache: false
        
    - name: Install EAS CLI
      run: npm install -g eas-cli
        
    - name: Build web version
      run: npx expo export --platform web
      
    - name: Fix asset paths for GitHub Pages
      run: |
        cd dist
        sed -i 's|href="/favicon.ico"|href="./favicon.ico"|g' index.html
        sed -i 's|src="/_expo/|src="./_expo/|g' index.html
        echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./index.html"></head><body></body></html>' > 404.html
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
      
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish EAS Update
      run: npx eas update --branch main --message "Update from GitHub Actions"